### ISSUE TITLE
Install issue on Debian

### ISSUE THREAD

**Issue by lanhin** [jcf94/vizgraph#1]
Hi there,
    I tried to use vizgraph on my Debian OS. As showed in README, I used `npm install`. But it returned a 404 error as follows. It seems that the install of electron failed. Anybody can help? 
    Thanks!

```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'electron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "--save-dev"
npm ERR! cwd /home/linhan/Documents/vizgraph
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/linhan/Documents/vizgraph/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jcf94** [comment]
@lanhin 
It seems that the package `types/node` is supported for npm version at least 2 in Debian.

The node.js & npm version are different in windows & linux.
For example, your Debian shows:
```
node -v v0.10.29
npm -v 1.4.21
```
But in my Windows, it shows:
```
node -v v8.7.0
npm -v 5.4.2
```

**Comment by lanhin** [comment]
@jcf94 
Thanks. I'll try a new version of that.

**Comment by jcf94** [comment]
@lanhin 
The Node.js version of yours is really far too old.
Actually I'm really surprised about it, because even in the  Centos( which is considered to be having a old software repo to keep system stable), we have:
```
node -v v6.12.0
npm -v 3.10.10
```
And it worked well.

Download a [new version of Node.js](https://nodejs.org/en/download/) will be helpful.
